# Generated by Django 6.0.1 on 2026-02-01 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name', max_length=255)),
                ('description', models.TextField(help_text='Detailed course description')),
                ('category', models.CharField(help_text='Course category (e.g., AI, Python, Web Development)', max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('duration_hours', models.IntegerField(blank=True, help_text='Estimated duration in hours', null=True)),
                ('prerequisites', models.TextField(blank=True, help_text='Any prerequisites or recommended prior knowledge')),
                ('learning_outcomes', models.TextField(blank=True, help_text='What students will learn (comma-separated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='enrolled', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Percentage of course completed')),
                ('resources_completed', models.IntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resource title', max_length=255)),
                ('description', models.TextField(help_text='What this resource covers')),
                ('resource_type', models.CharField(choices=[('documentation', 'Documentation'), ('tutorial', 'Tutorial'), ('article', 'Article'), ('interactive', 'Interactive Learning'), ('book', 'Book'), ('course', 'Online Course'), ('repository', 'GitHub Repository'), ('podcast', 'Podcast'), ('tool', 'Tool/Framework'), ('practice', 'Practice Problems')], max_length=50)),
                ('url', models.URLField(help_text='URL to the resource')),
                ('platform', models.CharField(help_text='Platform (e.g., freeCodeCamp, MDN, Stack Overflow)', max_length=100)),
                ('duration_hours', models.IntegerField(blank=True, help_text='Duration in hours (if applicable)', null=True)),
                ('quality_rating', models.CharField(choices=[('excellent', '⭐⭐⭐⭐⭐ Excellent'), ('very_good', '⭐⭐⭐⭐ Very Good'), ('good', '⭐⭐⭐ Good'), ('fair', '⭐⭐ Fair')], default='good', help_text='Quality rating (curated assessment)', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_free', models.BooleanField(default=True, help_text='Is this resource free?')),
                ('is_official', models.BooleanField(default=False, help_text='Is this official documentation/resource?')),
                ('is_trending', models.BooleanField(default=False, help_text='Is this a trending/popular resource?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_added', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='users.course')),
            ],
            options={
                'ordering': ['-quality_rating', '-is_official', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', 'status'], name='users_cours_user_id_b27881_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'level'], name='users_cours_categor_5afc31_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'status'], name='users_cours_user_id_e1ec49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['course', 'resource_type'], name='users_cours_course__809b22_idx'),
        ),
        migrations.AddIndex(
            model_name='courseresource',
            index=models.Index(fields=['is_free', 'is_trending'], name='users_cours_is_free_50f9dd_idx'),
        ),
    ]
