# Generated by Django 6.0.1 on 2026-01-31 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('concept_score', models.FloatField(default=0.0)),
                ('logic_score', models.FloatField(default=0.0)),
                ('execution_score', models.FloatField(default=0.0)),
                ('error_patterns', models.JSONField(blank=True, default=list)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_skill', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('question_type', models.CharField(choices=[('QUIZ', 'Quiz (MCQ)'), ('OUTPUT', 'Guess Output'), ('CODE', 'Coding Problem')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.skill')),
            ],
        ),
        migrations.CreateModel(
            name='OutputGuessSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.FloatField(help_text='Time taken to answer this specific question')),
                ('predicted_output', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submissions', to='assignments.assignmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputGuessQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('correct_output', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_data', to='assignments.question')),
            ],
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.FloatField(help_text='Time taken to answer this specific question')),
                ('submitted_code', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('passed_test_cases', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('correctness_score', models.FloatField(default=0.0)),
                ('time_perf_score', models.FloatField(default=0.0)),
                ('optimality_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('execution_time_ms', models.FloatField(null=True)),
                ('memory_usage_kb', models.FloatField(null=True)),
                ('complexity_analysis', models.CharField(blank=True, max_length=50)),
                ('complexity_rank', models.IntegerField(default=3, help_text='1=O(n), 2=O(nlogn), 3=O(n^2), 4=O(n^3)')),
                ('testcases_passed_percentage', models.FloatField(default=0.0)),
                ('code_runs', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submissions', to='assignments.assignmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('constraints', models.TextField(blank=True)),
                ('test_cases', models.JSONField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_data', to='assignments.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options', models.JSONField(help_text="Format: [{'id': 'a', 'text': 'Option A'}, ...]")),
                ('correct_option_id', models.CharField(max_length=50)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_data', to='assignments.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.FloatField(help_text='Time taken to answer this specific question')),
                ('selected_option_id', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_submissions', to='assignments.assignmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
