# Generated by Django 6.0.1 on 2026-02-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='module2_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='concept_tag',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
