# Generated by Django 6.0.1 on 2026-01-31 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GapAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('primary_gap', models.CharField(help_text='The root cause learning gap identified.', max_length=255)),
                ('secondary_gap', models.CharField(blank=True, help_text='Secondary areas of improvement.', max_length=255)),
                ('confidence_level', models.FloatField(help_text='Confidence in the analysis (0-100%).')),
                ('recommendation', models.TextField(help_text='Personalized recommendation for the student.')),
                ('skill_traversal_path', models.JSONField(default=list, help_text='Path traversed in dependency graph.')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='assignments.assignmentattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('STRONG', 'Strong'), ('WEAK', 'Weak'), ('GAP', 'Gap Detected')], max_length=10)),
                ('score_impact', models.FloatField(default=0.0, help_text='How much this skill impacted the score.')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_analyses', to='analysis.gapanalysisreport')),
            ],
        ),
    ]
